### ISSUE TITLE
about pty.fork() function

### ISSUE THREAD

**Issue by weijiang1994** [cs01/pyxtermjs#14]
**Hello**
I need to implement a web terminal base on flask and **use the factory mode to start up** the app.
My question is what time the `pty.fork() function child_pid equal zero`?

your code 
```python
(child_pid, fd) = pty.fork()
    if child_pid == 0:
        # this is the child process fork.
        # anything printed here will show up in the pty, including the output
        # of this subprocess
        subprocess.run(app.config["cmd"])
    else:
        # this is the parent process fork.
        # store child fd and pid
        app.config["fd"] = fd
        app.config["child_pid"] = child_pid
        set_winsize(fd, 50, 50)
        cmd = " ".join(shlex.quote(c) for c in app.config["cmd"])
        print("child pid is", child_pid)
        print(
            f"starting background task with command `{cmd}` to continously read "
            "and forward pty output to client"
        )
        socketio.start_background_task(target=read_and_forward_pty_output)
        print("task started")

```
In my application, I can't launch the subprocess.

**Comment by cs01** [comment]
The `pty.fork()` call splits into two processes: the same current (parent) process, and a new child process. The child process has the pid reported 0. 

https://docs.python.org/3/library/pty.html#pty.fork
https://www.tutorialspoint.com/unix_system_calls/fork.htm

> Fork. Connect the child’s controlling terminal to a pseudo-terminal. Return value is (pid, fd). Note that the child gets pid 0, and the fd is invalid. The parent’s return value is the pid of the child, and fd is a file descriptor connected to the child’s controlling terminal (and also to the child’s standard input and output).

The `subprocess.run` call should be changed to `os.execvp` (https://docs.python.org/3/library/os.html#os.execvp). This will actually swap out the child process with whatever you are running:

> These functions all execute a new program, replacing the current process; they do not return. On Unix, the new executable is loaded into the current process, and will have the same process id as the caller. Errors will be reported as OSError exceptions.

**Comment by weijiang1994** [comment]
My OS is ubuntu 18.04, I change the `pty.fork()` to `os.forkpty()`, then it is running.
I don't know why I can't use the `pty.fork()` function.  When I use the `pty.fork()` function, I can't go into the `if` condition,That say child_pid not equal to zero.

**My program code below here.**
```python
    (child_pid, fd) = os.forkpty()
    # print('child pid:', child_pid)
    if child_pid == 0:
        os.execl('/usr/bin/ssh', 'ssh', '-p', str(22), '{}@{}'.format(host.host_name, host.ip))
    else:
        session[username] = {}
        session[username]['child_pid'] = child_pid
        session[username]['fd'] = fd
        session[username]['room_id'] = rooms()[0]
        session.modified = True
        socketio.start_background_task(read_and_forward_pty_output, fd, child_pid, rooms()[0])
```

**Comment by cs01** [comment]
I don't know either. According to Python's docs:

https://docs.python.org/3/library/os.html#os.forkpty (emphasis mine)

> Fork a child process, using a new pseudo-terminal as the child’s controlling terminal. Return a pair of (pid, fd), where pid is 0 in the child, the new child’s process id in the parent, and fd is the file descriptor of the master end of the pseudo-terminal. **For a more portable approach, use the pty module.** If an error occurs OSError is raised.

The fact that one works and one doesn't sounds like it might be a bug in Python. In any case, it looks like you got things working on your own branch. You might want to file a bug on Python's issue tracker. https://bugs.python.org/

**Comment by weijiang1994** [comment]
> I don't know either. According to Python's docs:
> 
> https://docs.python.org/3/library/os.html#os.forkpty (emphasis mine)
> 
> > Fork a child process, using a new pseudo-terminal as the child’s controlling terminal. Return a pair of (pid, fd), where pid is 0 in the child, the new child’s process id in the parent, and fd is the file descriptor of the master end of the pseudo-terminal. **For a more portable approach, use the pty module.** If an error occurs OSError is raised.
> 
> The fact that one works and one doesn't sounds like it might be a bug in Python. In any case, it looks like you got things working on a fork. You might want to file a bug on Python's issue tracker. https://bugs.python.org/

Ok, thank you so much!
