### ISSUE TITLE
Support for custom CSS

### ISSUE THREAD

**Issue by CoconutMacaroon** [cs01/pyxtermjs#24]
I'd like a command-line argument that lets me specify a custom CSS file to use. For example, I might want to use some CSS that changes the way that the connected/disconnected looks, or I might want to specify a specific font for part of it.

Can a feature please be added to support adding custom CSS into pyxter.js?

**Comment by cs01** [comment]
This project is not really actively developed. Feel free to fork it and give it a shot if you like.

**Comment by CoconutMacaroon** [comment]
That's fine, thanks for responding!
