### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by wmmihaa** [cs01/pyxtermjs#33]
Hi Chad,
We are using a similar xtermjs application using node js (node-pty) to host the terminal process and SignalR for communication with the web host. I’ve been looking at doing the same thing using python for about a year (!) until I came across pyxtermjs and was super existed. 

I’m not a python guru by any means, but I got most of it working, but I got stuck on the initiation where I run into some issues which seems related to threading.
What would it take to get an hour of your time to see if you can point me in the right direction? I’m not looking for a free-bee. I’m happy to reimburse you since I’m really stuck right now.

You can reach me a mikael dot hakansson at axians dot com. or on twitter @wmmihaa

Cheers
Mikael

**Comment by cs01** [comment]
Closing as we connected via another website
