### ISSUE TITLE
[Question] Pyxtermjs integration

### ISSUE THREAD

**Issue by nerkdesign** [cs01/pyxtermjs#34]
Hi guys,

thanks for this amazing tool,
I wanted to integrate pyxtermjs on an existing python script already using flask (to avoid to use a reverse proxy using 2 ports)
Is there a simple way for this integration?

Many thanks

**Comment by cs01** [comment]
There are no apis in this tool or extension points to use with other tools. 

You are free to clone the code and use it however you like. It’s a pretty small program so that’s probably your best bet.
