### ISSUE TITLE
How to handle more than one pty child process fork?

### ISSUE THREAD

**Issue by Avinash-Raj** [cs01/pyxtermjs#5]
I'm in a situation where I have to create child pty fork  for each user session.  I exactly followed your approach and it's working great but text delay (while on emitting the pty output) happens if more than 3 sessions got opened (in the background it created three child processes). Please help me to overcome this situation. Does making use of async func would help? or do we have to use any low level functions like `os.wait()` or `os.waitpid()` ?

**Comment by cs01** [comment]
> Does making use of async func would help?

Yes this should help. 

You can use the `add_reader()` method to do this. https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_reader

Something like 
```
def handle_new_data(fd):
        output = os.read(fd, max_read_bytes).decode()
        socketio.emit("pty-output", {"output": output}, namespace="/pty")

loop = asyncio.get_event_loop()
loop.add_reader(app.config["fd"], handle_new_stdin, fd)
```

**Comment by cs01** [comment]
I have successfully connected to > 5 terminals from the browser in another project of mine called TermPair: https://github.com/cs01/termpair

TermPair is built around async, so you can check that out for an example if you want.

**Comment by Avinash-Raj** [comment]
Your code w.r.t `loop.add_reader` is not working for me. Actually I'm using python-socketio library in a django project (https://github.com/miguelgrinberg/python-socketio/tree/master/examples/server/wsgi/django_example) . See this is a synchronous code which uses threads for running  background task.

Tried async example also https://github.com/miguelgrinberg/python-socketio/blob/master/examples/server/asgi/app.py, it works but somehow I'm experiencing blocking in the (read from fd) code (ie. delay in emitting fd data when 3 or more child process created through `pty.fork()`).

```python
async def read_and_forward_output(fd=None, sid=None):
    max_read_bytes = 1024 * 20
    # put initial sleep for 0.5 secs
    await sio.sleep(0.5)
    while True:
        await sio.sleep(0.1)
        if fd:
            timeout_sec = 0.1
            (data_ready, _, _) = select.select([fd], [], [], timeout_sec)
            if data_ready:
                output = os.read(fd, max_read_bytes).decode()
                await sio.emit("sql-output", {"output": output}, room=sid)

sio.start_background_task(target=read_and_forward_output, fd=fd, sid=sid)
```

**Comment by cs01** [comment]
The `select.select` call will block for up to 0.1 seconds.

**Comment by Avinash-Raj** [comment]
Thanks, it got speeds up when changed the timeout to 0 sec.Another issue is, I can view only 4 or 5 lines on moving the scroll bar up. It fails to move further upwards. You may test this by writing 1000 lines on terminal. You can't reach the 1st line after done writing 1000 lines.

**Comment by cs01** [comment]
Glad you got it working!

The number of lines of history is configurable in xtermjs.  See https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#scrollback.

**Comment by MuhammedAliISIK** [comment]
> Your code w.r.t `loop.add_reader` is not working for me. Actually I'm using python-socketio library in a django project (https://github.com/miguelgrinberg/python-socketio/tree/master/examples/server/wsgi/django_example) . See this is a synchronous code which uses threads for running background task.
> 
> Tried async example also https://github.com/miguelgrinberg/python-socketio/blob/master/examples/server/asgi/app.py, it works but somehow I'm experiencing blocking in the (read from fd) code (ie. delay in emitting fd data when 3 or more child process created through `pty.fork()`).
> 
> ```python
> async def read_and_forward_output(fd=None, sid=None):
>     max_read_bytes = 1024 * 20
>     # put initial sleep for 0.5 secs
>     await sio.sleep(0.5)
>     while True:
>         await sio.sleep(0.1)
>         if fd:
>             timeout_sec = 0.1
>             (data_ready, _, _) = select.select([fd], [], [], timeout_sec)
>             if data_ready:
>                 output = os.read(fd, max_read_bytes).decode()
>                 await sio.emit("sql-output", {"output": output}, room=sid)
> 
> sio.start_background_task(target=read_and_forward_output, fd=fd, sid=sid)
> ```

can you please share the rest of your code? i get "TypeError: 'coroutine' object is not iterable" when i try to implement this solution.
