### ISSUE TITLE
remove pkg-resources==0.0.0 from requirements.txt

### ISSUE THREAD

**Issue by drewwebster** [cs01/pyxtermjs#7]
following install directions, pip install -r requirements, got error

  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 7)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 7))

Fixed by removing line pkg-resources==0.0.0 from requirements.txt

**Comment by YitziG** [comment]
Are you certain that it is safe to remove?

**Comment by cs01** [comment]
It's already been removed. Closing.
